version: '3.8'

services:
  api:
    # 0. NOMBRE DE LA IMAGEN (opcional, si no agarra el nombre de la carpeta enla que este).
    image: heroes-villanos-fastapi:latest
    # 1. Le dice a Compose que construya la imagen usando el Dockerfile en este directorio.
    build: . 
    
    # 2. Le asigna un nombre de contenedor legible.
    container_name: api-heroes-villanos
    
    # 3. Mapeo de puertos (8000 de tu PC al 80 del contenedor).
    ports:
      - "8000:80"
      
    # 4. VOLUMEN: Monta la carpeta de tu PC (el .) en el /app del contenedor.
    #    Esto permite que los cambios en main.py sean leídos instantáneamente.
    volumes:
      - .:/app
      
    # 5. COMANDO: Inicia Uvicorn con la opción --reload.
    #    Al guardar main.py en tu PC, el servidor se reinicia automáticamente.
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    
    # 6. VINCULAR CON LA BASE DE DATOS
    depends_on:
      db:
        condition: service_healthy # <--- Espera a que el healthcheck pase
      
    # 7. ¡CRUCIAL! INYECTAR LA VARIABLE DE ENTORNO
    environment:
      # La URL de conexión al servicio 'db'
      # postgresql://usuario:contraseña@nombre_del_servicio:puerto/nombre_db
      - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/heroes_db
      - API_CLAVE_SECRETA=clave-secreta-para-desarrollo-local-818
  db:
    # 8. SERVICIO DE BASE DE DATOS POSTGRESQL
    image: postgres:14-alpine
    container_name: heroes_db_container
    restart: always # Asegura que la DB se reinicie si falla
    
    # 9. CREDENCIALES DE LA DB
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: heroes_db
      
    # 10. PERSISTENCIA DE DATOS: Montar un volumen para que los datos no se borren
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d heroes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
# 11. DEFINICIÓN DEL VOLUMEN PERSISTENTE
volumes:
  postgres_data: